# Generated by Django 3.1.7 on 2021-04-21 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('level', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Moderado', 'Moderado'), ('Avançado', 'Avançado')], max_length=10, verbose_name='Dificuldade')),
                ('n_series', models.PositiveSmallIntegerField(verbose_name='Número de Séries')),
                ('n_reps', models.PositiveSmallIntegerField(verbose_name='Número de Repetições')),
                ('avg_interval', models.PositiveIntegerField(verbose_name='Intervalo médio')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_level', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Moderado', 'Moderado'), ('Avançado', 'Avançado')], max_length=10, verbose_name='Dificuldade média')),
                ('body_part', models.CharField(max_length=100, verbose_name='Parte do Corpo')),
                ('exercise', models.ManyToManyField(related_name='exercise', to='core.Exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem')),
                ('text', models.TextField(verbose_name='Texto do artigo')),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
        ),
    ]
