# Generated by Django 3.1.7 on 2021-04-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210421_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
