# Generated by Django 3.1.7 on 2021-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workout',
        ),
        migrations.AddField(
            model_name='user',
            name='workout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
