# Generated by Django 3.1.7 on 2021-04-25 22:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210424_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_comentario', models.CharField(max_length=100)),
                ('texto_comentario', models.TextField()),
                ('data_comentario', models.DateField(default=datetime.datetime(2021, 4, 25, 22, 38, 35, 419284, tzinfo=utc))),
                ('publicado_comentario', models.BooleanField(default=False)),
                ('artigo_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('autor_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
