# Generated by Django 3.1.7 on 2021-04-25 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
