# Generated by Django 3.1.7 on 2021-05-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210425_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='artigo_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='core.article'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
