# Generated by Django 3.1.7 on 2021-03-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
