# Generated by Django 3.1.7 on 2021-04-06 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_article_autor_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='autor_post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='Teste', on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='core.category', verbose_name='Categoria'),
        ),
    ]
